image:
  # Will be added from helm command
  repository: ""
  pullPolicy: Always
  tag: ""

app:
  logLevel: "info"

db:
  protocol: postgresql+asyncpg
  port: 5432
  user: user
  dbName: db
  connectionPool:
    size: 1
    timeout: 10
    recycleAfter: 1000
  ssl:
    enabled: true
    verifyCertificate: false
