app:
  environment: prod

image:
  pullPolicy: IfNotPresent

db:
  host: 172.24.96.5

api:
  replicaCount: 3
  resources:
    limits:
      memory: 512Gi
    requests:
      cpu: 400m
      memory: 256Mi
