cluster:
  gcpProjectID: microservice-template-475915

image:
  # Will be added from helm command
  repository: ""
  tag: ""

resources:
  limits:
    cpu: 300m
    memory: 256Mi
  requests:
    cpu: 150m
    memory: 128Mi

app:
  logLevel: "info"

db:
  protocol: postgresql+asyncpg
  port: 5432
  user: user
  dbName: db
  connectionPool:
    size: 1
    timeout: 10
    recycleAfter: 1000
  ssl:
    enabled: true
    verifyCertificate: false


api:
  replicaCount: 2
  serverWorkers: 2
  service:
    type: LoadBalancer
  ingress:
    host: "insert-your-domain-here"
    path: "/"
