services:
  api:
    build:
      context: .
      target: dev
      network: host
    environment:
      APP_ENV: local
      LOG_LEVEL: info
      DB_PROTOCOL: postgresql+asyncpg  # or mysql+aiomysql
      SENTRY_DSN: "https://4af4a5c17aff72f702472e40a4b529dd@o4510357795438592.ingest.de.sentry.io/4510357797470288"
      DB_HOST: postgres  # or mysql
      DB_PORT: 5432  # or 3306
      DB_NAME: db
      DB_USER: user
      DB_PASSWORD: swordfish
      DB_POOL_SIZE: 1
      DB_POOL_TIMEOUT: 10
      DB_POOL_RECYCLE: 1800
      DB_QUERY_RETRY_COUNT: 3
      DB_QUERY_RETRY_WAIT_ARGS: '{ "factor": 0.1, "base": 1.5 }'
    ports:
      - "5000:80"
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./alembic:/app/alembic
      - ./pyproject.toml:/app/pyproject.toml
    depends_on:
      - postgres

  postgres:
    image: postgres:18-alpine
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: swordfish
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  mysql:
    image: mysql:9.4
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: swordfish
      MYSQL_ROOT_PASSWORD: swordfish
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uuser -p$${MYSQL_PASSWORD} --silent"]
      interval: 5s
      timeout: 5s
      retries: 5
