apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.prefix" . }}api
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.api.service.annotations | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }} api
