apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: api
spec:
  parentRefs:
    - kind: Gateway
      name: gateway
      namespace: gateway
  hostnames:
    - {{ .Values.env }}.{{ .Values.app.domain }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: {{ .Values.api.route.path }}
      backendRefs:
        - name: api
          port: 80
