{{- if .Values.api.ingress }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "chart.prefix" . }}api
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
{{- if .Values.api.ingress.tlsEnabled }}
    cert-manager.io/cluster-issuer: "letsencrypt"
{{- end }}
spec:
  ingressClassName: nginx
{{- if .Values.api.ingress.tlsEnabled }}
  tls:
    - hosts:
        - {{ .Values.api.ingress.host }}
      secretName: {{ include "chart.prefix" . }}api-tls
{{- end }}
  rules:
  - http:
      paths:
        - pathType: Prefix
          path: {{ .Values.api.ingress.path }}
          backend:
            service:
              name: {{ include "chart.prefix" . }}api
              port:
                number: 80
  {{- if .Values.api.ingress.host }}
    host: {{ .Values.api.ingress.host }}
  {{- end }}

{{- end }}
