{{- if .Values.api.ingress }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "chart.prefix" . }}api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
        - pathType: Prefix
          path: {{ .Values.api.ingress.path }}
          backend:
            service:
              name: {{ include "chart.prefix" . }}api
              port:
                number: 80
  {{- if .Values.api.ingress.host }}
    host: {{ .Values.api.ingress.host }}
  {{- end }}

{{- end }}
