apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.prefix" . }}api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.api.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: 80
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }} api
