apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-migrate-db
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-install,pre-upgrade
    helm.sh/hook-weight: "1"
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-migrate-db
      labels:
        {{- include "chart.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: migrate-db
          {{- include "chart.imageAndResources" (dict "root" .Values "ctx" .) | nindent 10 }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-common
            - secretRef:
                name: {{ .Release.Name }}-secret
          command: [ "alembic", "upgrade", "head" ]
