apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "chart.prefix" .}}migrate-db
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-install,pre-upgrade
    helm.sh/hook-weight: "1"
spec:
  template:
    metadata:
      name: {{ include "chart.prefix" . }}migrate-db
      labels:
        {{- include "chart.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: migrate-db
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "chart.image" . }}
          envFrom:
            - configMapRef:
                name: {{ include "chart.prefix" . }}common
            - secretRef:
                name: {{ include "chart.prefix" . }}secret
          command: [ "alembic", "upgrade", "head" ]
