apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "1"
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: external-secrets
    kind: SecretStore
  target:
    name: {{ .Release.Name }}-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Release.Namespace }}-db-password
        version: latest
