apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "chart.prefix" . }}secret
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "1"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: {{ include "chart.prefix" . }}secret
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.env }}-db-password
    - secretKey: BEARER_TOKEN
      remoteRef:
        key: {{ .Values.env }}-bearer-token
