apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "chart.prefix" . }}secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Chart.Name }}
    kind: ClusterSecretStore
  target:
    name: {{ include "chart.prefix" . }}secret
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: db-password
        version: latest
