projectId: microservice-template-475915
clusterName: cluster
clusterLocation: europe-central2
kubernetesContext: microservice

namespaces:
  - microservice-dev
  - microservice-prod

grafana:
  prometheusUrl: "https://prometheus-prod-65-prod-eu-west-2.grafana.net/api/prom/push"
  prometheusUsername: "2809059"
  lokiUrl: "https://logs-prod-012.grafana.net/loki/api/v1/push"
  lokiUsername: "1400207"
