{{- range $namespace := .Values.namespaces }}
{{- with $ }}

---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: external-secrets
  namespace: {{ $namespace }}
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.project_id }}
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: external-secrets
            namespace: {{ $namespace }}

{{- end }}
{{- end }}
